"""add stdout to test_execution

Revision ID: 2f103e3bd2e3
Revises: 2358db0c5c13
Create Date: 2026-05-11 12:03:04.780843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f103e3bd2e3'
down_revision: Union[str, Sequence[str], None] = '2358db0c5c13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_executions', sa.Column('stdout', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_executions', 'stdout')
    # ### end Alembic commands ###
